# Generated by Django 3.2 on 2021-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincycle',
            name='auto_click_power',
            field=models.IntegerField(default=0),
        ),
    ]
