# Generated by Django 3.2 on 2021-05-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210511_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincycle',
            name='boostPrice',
            field=models.IntegerField(default=10),
        ),
    ]
