# Generated by Django 3.2 on 2021-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_boost_boost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincycle',
            name='toNextLevel',
            field=models.IntegerField(default=10),
        ),
    ]
